# Generated by Django 5.0.3 on 2025-09-21 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#cccccc', help_text='Hex color code for UI display', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Task Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Task Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Time')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='myapp.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='myapp.tasktag')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['priority', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='myapp_task_status_618b24_idx'), models.Index(fields=['priority'], name='myapp_task_priorit_824c00_idx'), models.Index(fields=['due_date'], name='myapp_task_due_dat_68da50_idx')],
            },
        ),
    ]
