# Generated by Django 5.2.7 on 2025-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_myapp_blogp_author__1ed7bd_idx_myapp_blogp_author_d4d002_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
