
SHOW_ROLE = 'show_role'
CREATE_ROLE = 'create_role'
READ_ROLE = 'read_role'
UPDATE_ROLE = 'update_role'
DELETE_ROLE = 'delete_role'
SHOW_USER = 'show_user'
CREATE_USER = 'create_user'
READ_USER = 'read_user'
UPDATE_USER = 'update_user'
DELETE_USER = 'delete_user'
TOGGLE_USER = 'toggle_user'
READ_AUCTION = 'read_auction'