# Generated by Django 5.2.7 on 2025-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tag_updated_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='myapp_blogp_author_d4d002_idx',
            old_name='myapp_blogp_author__1ed7bd_idx',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
